### ISSUE TITLE
FPFC toggle enabled in SiraUtil results in camera stuck in floor when testing a map using fpfc

### ISSUE THREAD

**Issue by Fatalution** [kinsi55/CS_BeatSaber_Camera2#37] opened 2021-06-11 16:11 UTC
When FPFC is enabled in the launch options and FPFC toggle is enabled in SitaUtil.json, the camera will be stuck in floor when testing a map.

This bug is only present in the latest version of Camera2.

Config: [Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6639756/Camera2.zip)

Steps to reproduce:
1. Update Camera2 to the latest version
2. Make sure FPFCToggle is set to enabled in SiraUtil.json
3. Launch the game with FPFC in launch options
4. Hop into any map
5. Enjoy being stuck in the floor
6. Roll back to the previous Camera2 version
7. Enjoy being unstuck

**Comment by kinsi55** [comment] 2021-06-11 17:05
If you have FPFC Toggle, why would you have fpfc in the launch options?

**Comment by kinsi55** [comment] 2021-06-11 17:11
That being said tho, I just tried to reproduce this. I'M on 1.16.2 and have the latest release from yesterday (.36) and cannot reproduce it.

**Comment by kinsi55** [comment] 2021-06-11 17:25
Actually I think I might know whats going on, I suppose you have your HMD plugged in while I dont which is why I cant reproduce it. I'll give you a test version in a second

**Comment by Fatalution** [comment] 2021-06-11 17:38
> Actually I think I might know whats going on, I suppose you have your HMD plugged in while I dont which is why I cant reproduce it. I'll give you a test version in a second

Actually, I always have my HMD unplugged when using FPFC mode. So no, it's unplugged

**Comment by kinsi55** [comment] 2021-06-11 17:58
Fixed in v0.3.37

**Closed by kinsi55** 2021-06-11 17:58 UTC
Labels: bug, unconfirmed
