### ISSUE TITLE
Discord isn't able to detect video to stream

### ISSUE THREAD

**Issue by B-u-r-a-G** [kinsi55/CS_BeatSaber_Camera2#4] opened 2021-02-24 13:15 UTC
Streaming beat saber to discord isn't possible. Stream is stuck on minimised window message.

**Comment by kinsi55** [comment] 2021-02-24 16:37
I'm unable to reproduce this, various others using Cam2 also dont experience this issue. Are you sure its not possibly something related to your setup? Have you tried rebooting? Maybe start Discord as Admin?

**Comment by kinsi55** [comment] 2021-03-09 01:03
Closing this as nobody I asked was able to reproduce it and I dont see how Cam2 would cause such a thing.

**Closed by kinsi55** 2021-03-09 01:03 UTC
Labels: bug, help wanted, unconfirmed
