### ISSUE TITLE
Wall in replays

### ISSUE THREAD

**Issue by Hatchet85014** [kinsi55/CS_BeatSaber_Camera2#41] opened 2021-07-05 05:19 UTC
Whenever im watching a replay, a wall shows up in the middle of my avatar, thus failing the level. sometimes it doesnt fail the level.
![image_2021-07-04_221628](https://user-images.githubusercontent.com/75503338/124421041-7ad89c80-dd15-11eb-898c-b5ab488231e0.png), such as shown here. 
here is my config:
{
  "visibleObjects": {
    "Walls": "Visible",
    "Debris": true,
    "UI": true,
    "Avatar": "Visible",
    "Floor": true,
    "CutParticles": true,
    "Notes": "Visible"
  },
  "type": "FirstPerson",
  "FOV": 101.729996,
  "layer": 1,
  "antiAliasing": 2,
  "renderScale": 1.3,
  "orthographic": false,
  "farZ": 1000.0,
  "viewRect": {
    "x": 0.0,
    "y": 0.0,
    "width": -1.0,
    "height": -1.0
  },
  "Multiplayer": {
    "followSpectatorPlattform": true
  },
  "Smoothfollow": {
    "position": 10.0,
    "rotation": 5.0,
    "forceUpright": false,
    "followReplayPosition": true,
    "pivotingOffset": true
  },
  "ModmapExtensions": {
    "autoOpaqueWalls": true,
    "autoHideHUD": true
  },
  "FPSLimiter": {
    "fpsLimit": 0
  },
  "targetPos": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "targetRot": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  }
}

**Comment by kinsi55** [comment] 2021-07-05 08:14
Does this happen without the avatar mod installed? Can you start the game, go into a replay (trigger the bug), then close the game and attach the _latest log file from the logs folder?

**Comment by kinsi55** [comment] 2021-08-23 14:56
This is a Bug of Transparent walls, passively caused by how Camera2 works. I've Let the Developer of that know, it will be fixed once that is updated.

**Closed by kinsi55** 2021-08-23 14:56 UTC
Labels: bug, unconfirmed
