### ISSUE TITLE
Broken Bloom Pre-Pass when Map features Cinema video

### ISSUE THREAD

**Issue by hamcoremusic** [kinsi55/CS_BeatSaber_Camera2#5] opened 2021-02-24 22:17 UTC
Hello!

I was just recording some songs on Beat Saber with Streamlabs OBS and notices after that every map I play has a CRAZY amount of fog that blocks about 80% of the lighting. This can be on maps with Mapping Extensions or even just regular ol' maps.

Here's a screenshot example of a significant point in the "Madeon - The Prince" map where all of the lights go technicolor and fill the screen. You can see that there is almost a white mist covering the entirety of the screen. 
![image](https://user-images.githubusercontent.com/28895283/109072838-91b21700-76c3-11eb-90e7-7ff7d11fa51e.png)

I tried a few more times on different songs and came out with the same result:
![image](https://user-images.githubusercontent.com/28895283/109072885-a5f61400-76c3-11eb-8a18-ac460ddfa85f.png)
![image](https://user-images.githubusercontent.com/28895283/109072924-b4443000-76c3-11eb-9237-4c4100c00072.png)

I don't know if this is a bug related to Camera2 or if it's from another plugin, I will attach my configs and my BSIPA log so you know what mods are running!

Camera2 Configs: [Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6039193/Camera2.zip)
latest.log: [_latest.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6039197/_latest.log)

All of these mas did have cinema enabled on it and I didn't try to do maps without it yet. I may update this post if I try another one later!

Thanks!

**Comment by kinsi55** [comment] 2021-02-24 22:22
Have you confirmed this happens only with Cam2? What if you try the Ingame Smoothcam?

And yeah if you could try removing Cinema, and Custom Platforms (Individually) if removing either of them isolates the issue that would be great!

**Comment by hamcoremusic** [comment] 2021-02-24 22:32
I JUST tried without Cinema and it worked haha. Looks like any map with a video in the background creates that nasty fog.

Here is the link to the mod: https://github.com/Kevga/BeatSaberCinema

Would you like me to post the issue there linking to here maybe? I don't really know who needs to make it compatible for who haha.

Again, this only happens when there IS a video, If I remove it, it looks fine.

**Comment by hamcoremusic** [comment] 2021-02-24 22:33
> Have you confirmed this happens only with Cam2? What if you try the Ingame Smoothcam?

I actually didn't get around to trying that to be honest. Would you like me to give that a go too?

**Comment by kinsi55** [comment] 2021-02-24 22:37
If its related to Cinema *maybe* it could be something special about your setup, so if you could confirm that it does not happen with the Smooth Cam that would be useful, then it'd be something I'd probably need to fix on my end

**Comment by hamcoremusic** [comment] 2021-02-24 22:39
Deleted Camera2 and it started looking okay while using Cinema. 
![image](https://user-images.githubusercontent.com/28895283/109075435-1bafaf00-76c7-11eb-9ef8-8f5a587b3ab2.png)

That being said, I have a hunch that maybe Cinema is rendering random fog after Z=0 (Mine is set to Z=-0.3). That's far fetched, but I could see it being something small like that for some reason haha

**Comment by kinsi55** [comment] 2021-02-24 22:40
Thats without Cam2 but base game smooth camera is enabled right?

**Comment by hamcoremusic** [comment] 2021-02-24 22:40
Ah crap I forgot to turn on smooth camera lol.... Would that matter in this case? I can hop back in if needed.

**Comment by kinsi55** [comment] 2021-02-24 22:41
Yeah when you dont enable the smooth camera Unity is just "re rendering" the HMD camera, smooth cam makes it a seperate camera.

**Comment by hamcoremusic** [comment] 2021-02-24 22:41
Okay! will investigate now.

**Comment by hamcoremusic** [comment] 2021-02-24 22:47
Works fine with Smooth Camera on

**Comment by kinsi55** [comment] 2021-02-24 22:48
Okay, if you could screenshot me your Graphics settings (Lower part) that might come in useful. Thanks for the troubleshooting I'll look into it!

**Comment by hamcoremusic** [comment] 2021-02-24 22:53
is this what you wanted? 
![image](https://user-images.githubusercontent.com/28895283/109076817-308d4200-76c9-11eb-8f68-b63e910a7af5.png)

**Comment by kinsi55** [comment] 2021-02-24 22:53
Yep thats correct, thank you.

**Comment by hamcoremusic** [comment] 2021-02-24 22:55
tried turning smoke off and got the same issue btw!

**Comment by kinsi55** [comment] 2021-02-24 22:57
Yeah I've seen this rendering issue before while developing Cam2, I've some idea what it could be cause by, just not sure yet what Cinema does to cause it.

**Comment by hamcoremusic** [comment] 2021-02-24 23:01
Feel free to drop dev versions for me to test here if you don't feel like getting Cinema yourself and setting it up!

**Comment by kinsi55** [comment] 2021-02-24 23:42
Seems like it is something that needs to be fixed in Cinema after all. I was unable to reproduce your *exact* issue but it was broken for me in a different way. Dakari made some changes which fixed it for me, feel free to give this a try and see if it fixes your problem. Keep in mind this is a WIP build and probably contains some issues.
[BeatSaberCinema.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6039500/BeatSaberCinema.zip)

**Comment by hamcoremusic** [comment] 2021-02-25 00:01
It's fixed for me!

**Comment by kinsi55** [comment] 2021-02-25 00:03
Kk, he'll be releasing this in an update eventually so keep look out for that.

**Closed by kinsi55** 2021-02-25 00:03 UTC
Labels: bug

**Comment by adamk33n3r** [comment] 2021-03-14 00:31
@hamcoremusic Hey, was just browsing the issues here and was wondering if you could tell me how you have the info display in the bottom left. It looks so clean!

**Comment by hamcoremusic** [comment] 2021-03-14 15:03
> @hamcoremusic Hey, was just browsing the issues here and was wondering if you could tell me how you have the info display in the bottom left. It looks so clean!

https://github.com/Reselim/beat-saber-overlay

**Comment by adamk33n3r** [comment] 2021-03-14 15:16
> > @hamcoremusic Hey, was just browsing the issues here and was wondering if you could tell me how you have the info display in the bottom left. It looks so clean!
> 
> https://github.com/Reselim/beat-saber-overlay

Gotcha, thank you. Was hoping it was actually in-game so that it could be seen on the monitor display but this is still neat! :)
