### ISSUE TITLE
Allow limiting the angles and positions to specific ranges

### ISSUE THREAD

**Issue by blackorbit1** [kinsi55/CS_BeatSaber_Camera2#82] opened 2022-08-12 10:09 UTC
Hello 👋

I thought the use of a 3rd person camera with a smooth following of the user was deliberately made more difficult for some technical reasons but seeing [TheBlackParrot](https://github.com/TheBlackParrot)'s post I though it could be a good idea to ask anyway.

I've seen in the code and on [TheBlackParrot](https://github.com/TheBlackParrot)'s streams that Attached cameras could allow such results but it looks like it's loosing support overtime and I found no documentation on how to use it. I've made a few experiments with the json file but never got anything usable.

I managed to have [a similar result](https://www.youtube.com/watch?v=ZSfjH75vZDs) using a first person camera and merging some parameters of a 3rd person camera in it but a lot of those parameters aren't accessible on the game menu and I can't see where the camera is ingame.

Maybe it could be interesting to either add the option to show the 1st person camera ingame and display more parameters if the attached camera is going to disappear or add an example of an Attached camera json file in the documentation 🙂

**Comment by kinsi55** [comment] 2022-08-12 15:15
If some settings are not accessible ingame it is for the reason that the vast majority of users don't need them. I don't want to have every single setting accessible ingame because already, many people are overwhelmed by the amount of options, thus advanced use cases like attached cameras will always stay something that you need to setup by editing the config.

Specifically for attached cameras you need to know how to use RUE and lookup game object names. That's not something that I want to support

**Comment by blackorbit1** [comment] 2022-08-13 11:35
Ok, I managed to have the Attached camera works, I didn't knew about all the gameObject things. 
And yeah this made me experience the issues raised in #80 which made me go back to my dirty solution.

This goes a bit out of the scope of this issue but I thought it could be cool to have a min / max rotation value, so the camera can show what we look at (without being super zoomed out) but don't rotate to much when we look at / speak to the viewers for instance.

Looking at the code it doesn't seems insane to implement to me but maybe I'm wrong. If you don't have much time for it I can try to do it and make a PR if it works but can't promise anything because I've never done any mod nor C#, and I don't even know how to compile the project 🥲

**Comment by kinsi55** [comment] 2022-08-13 16:17
With every option that I decide to add, I am making sure that its something at least a hand full of people do actually need. I dont want feature creep to be part of my projects even more than it already is - Yes being able to limit the range of values is not hard to add but its at least one, or even two values extra in the config per axis, and that just adds a lot of "trash" to the config most dont need

**Comment by kinsi55** [comment] 2022-08-13 22:42
I think I'll implement it in a way where theres a seperate locking section for fp / attached cameras, the values can either be integers in which case it will lock it to that value, or a string `min:max`

**Comment by kinsi55** [comment] 2022-08-13 23:15
Since this is now essentially a duplicate of #80 ill lock it

**Closed by kinsi55** 2022-08-13 23:15 UTC
Labels: documentation, question
