### ISSUE TITLE
incremental cam adjustment in game

### ISSUE THREAD

**Issue by OoDeeR** [kinsi55/CS_BeatSaber_Camera2#20] opened 2021-04-06 10:39 UTC
It's near impossible to get precise 3rd person angles by trying to adjust them with dragging the handle. I always find myself rather just editing the json file and rebooting than bothering with the in-game positioning.
I think some kind of numeric input or just incremental adjusting via arrow buttons for at least the rotation would be convenient.
Edit: referring to v0.3.6. Since I didn't see any mention of it in the recent version change logs, I assume this feature is not in the mod yet. If it is, please disregard.

**Comment by kinsi55** [comment] 2021-04-06 15:04
You don't need to restart the game to make adjustments to the config, you can reload them while the game is running w/ ctrl shift f1. Alternatively, you can move around positions ld cameras from FPFC as well.

**Comment by kinsi55** [comment] 2021-04-09 20:46
Closing as its a duplicate of #12

**Closed by kinsi55** 2021-04-09 20:46 UTC
Labels: question
